// ── dist/sitemap.xml, with lastmod derived from git ──
//
// This replaces a hand-maintained public/sitemap.xml whose dates drifted the
// moment anyone forgot to touch them: it still claimed 2026-07-24 for pages
// edited a week later. A stale lastmod is worse than none, because it tells a
// crawler not to bother re-reading a page that actually changed.
//
// lastmod now comes from `git log` over the files that produce each route
// (declared as `sources` in scripts/lib/site-data.mjs). That is a proxy, not a
// per-paragraph diff — the three case pages share src/data/projects.ts, so
// editing one bumps all three. It errs toward "recently touched", which costs
// a re-crawl, rather than toward a date frozen at whatever someone last typed.
//
// When git cannot answer (no repository, or a shallow clone whose single
// commit did not touch the file), the <lastmod> is omitted for that URL rather
// than filled with the build date. The sitemap spec makes the element
// optional, and inventing today's date for every page on every deploy would be
// a lie that also destroys the signal.

import { writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';

import { DIST_DIR, REPO_ROOT, buildRoutes } from './lib/site-data.mjs';

const OUT_FILE = join(DIST_DIR, 'sitemap.xml');

/** Author date (not commit date) of the newest commit touching any of `paths`, as YYYY-MM-DD. */
function lastModified(paths) {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%ad', '--date=short', '--', ...paths], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : null;
  } catch {
    return null;
  }
}

function urlEntry(route) {
  const lastmod = lastModified(route.sources);
  return [
    '  <url>',
    `    <loc>${route.canonical}</loc>`,
    ...(lastmod ? [`    <lastmod>${lastmod}</lastmod>`] : []),
    '    <changefreq>monthly</changefreq>',
    `    <priority>${route.priority}</priority>`,
    '  </url>',
  ].join('\n');
}

function main() {
  if (!existsSync(DIST_DIR)) {
    throw new Error(`build-sitemap: ${DIST_DIR} does not exist — run vite build first`);
  }

  // /privacy, /booking and /press are served noindex; listing them here would
  // contradict the pages themselves.
  const routes = buildRoutes().filter((route) => route.indexable);

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/build-sitemap.mjs — do not edit by hand.',
    '     URLs match the canonical tags emitted by scripts/prerender-routes.mjs:',
    '     trailing slashes throughout, since GitHub Pages 301s /route to /route/. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...routes.map(urlEntry),
    '</urlset>',
    '',
  ].join('\n');

  writeFileSync(OUT_FILE, xml);

  const dated = routes.filter((route) => lastModified(route.sources)).length;
  console.log(`build-sitemap: wrote dist/sitemap.xml — ${routes.length} URL(s), ${dated} with a git-derived lastmod.`);
  if (dated < routes.length) {
    console.warn('build-sitemap: some routes have no lastmod — git history is unavailable or shallow (needs fetch-depth: 0).');
  }
}

main();
